from data_sets_reporter.classes.data_set_reporter import DataSetReporter
from data_sets_reporter.depedency_injector.container import Container
from data_sets_reporter.classes.data_class.data_set_info_for_reporter import DataSetInfoForReporter

Reporter: DataSetReporter = Container.data_set_reporter
