from data_set_remover.classes.data_set_remover import DataSetRemover
from data_set_remover.depedency_injector.container import Container
from data_set_remover.classes.data_class.data_for_criteria_remove import DataForCriteriaRemove

Remover: DataSetRemover = Container.data_set_remover
